name: modulisto_flutter
description: An advanced state management solution with any number of event flows
version: 1.0.1
resolution: workspace
homepage: https://github.com/kitsuniru/modulisto
repository: https://github.com/kitsuniru/modulisto
issue_tracker: https://github.com/kitsuniru/modulisto/issues

topics:
  - architecture
  - state-management
  - state
  - concurrency
  - controller

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  modulisto: ^1.0.2
  meta: ^1.15.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0
  fake_async: ^1.3.1

