name: Setup
description: Sets up the Flutter environment

inputs:
  flutter-version:
    description: 'The version of Flutter to use'
    required: false
    default: '3.29.0'
  pub-cache:
    description: 'The name of the pub cache variable'
    required: false
    default: app

runs:
  using: composite
  steps:
    - name: 📦 Checkout the repo
      uses: actions/checkout@v4

    - name: 🚂 Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '${{ inputs.flutter-version }}'
        channel: "stable"
        cache: true

    - name: 📤 Restore Pub modules
      id: cache-pub-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          /home/runner/.pub-cache
        key: ${{ runner.os }}-pub-${{ inputs.pub-cache }}-${{ hashFiles('pubspec.lock') }}

    - name: 👷 Install Dependencies
      shell: bash
      run: |
        echo /home/runner/.pub-cache/bin >> $GITHUB_PATH
        flutter config --no-cli-animations --no-analytics
        flutter pub get

    - name: 📥 Save Pub modules
      id: cache-pub-save
      if: steps.cache-pub-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          /home/runner/.pub-cache
        key: ${{ steps.cache-pub-restore.outputs.cache-primary-key }}
