name: Codecheck command

on:
  issue_comment:
    types: [created]

  pull_request:

jobs:
  code_check:
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/codecheck') &&
      (${{ github.event.comment.user.login }} == ${{ github.repository_owner }})
    uses: arxdeus/github_workflows/.github/workflows/dart_monorepo_code_check.yaml@main
