name: Checkout

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - "**"

permissions:
  contents: read
  actions: read
  checks: write

env:
  FLUTTER_TEST_REPORT: ${{github.workspace}}/flutter-test-report.json

jobs:
  code_check:
    uses: arxdeus/github_workflows/.github/workflows/dart_monorepo_code_check.yaml@main
