name: Checkout

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"
      - "develop"
      - "feature/**"
      - "bugfix/**"
      - "hotfix/**"
      - "support/**"
    paths:
      - "**/pubspec.yaml"
      - "**/pubspec.lock"
      - "packages/**/lib/**.dart"
      - "packages/**/test/**.dart"
      - "example/**.dart"

permissions:
  contents: read
  actions: read
  checks: write

env:
  FLUTTER_TEST_REPORT: ${{github.workspace}}/flutter-test-report.json

jobs:
  code_check:
    uses: arxdeus/github_workflows/.github/workflows/dart_monorepo_code_check.yaml@main
