name: Publish
permissions:
  contents: write
on:
  push:
    tags:
      - '*-v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write
  id-token: write
  actions: read
  checks: write


jobs:
  publish:
    uses: arxdeus/github_workflows/.github/workflows/dart_monorepo_publish.yaml@main
