name: Publish
permissions:
  contents: write
  id-token: write
on:
  workflow_call:
    inputs:
      package-name:
        type: string
        description: Which package to publish
        required: true
      package-version:
        type: string
        default: '0.0.0'
        required: true
  workflow_dispatch:
    inputs:
      package-name:
        type: choice
        description: Which package to publish
        required: true
        options:
        - modulisto
        - modulisto_flutter
      package-version:
        type: string
        default: '0.0.0'
        required: true
jobs:
  publish:
    uses: arxdeus/github_workflows/.github/workflows/dart_monorepo_publish.yaml@main
